[project]
name = "week02"
version = "0.1.0"
description = "AI工程化训练营第二周项目"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
	"fastapi>=0.112.0",
	"uvicorn>=0.30.6",
	"ms-swift==3.*",
	"torch<=2.7.1",
	"numpy==1.24.3",
	"gradio==5.*"
]

